In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os 
os.getcwd()

'd:\\git_local_repository\\yangoos57\\ML\\[inria] scikit-learn course'

## Encoding of categorical variables

### ordinal encoding

### one-hot encoding

In [2]:
adult_df = pd.read_csv('data/phpMawTba.csv').drop(columns='education-num')

target = adult_df['class']
data = adult_df.drop(columns=['class'])

In [8]:
from sklearn.compose import make_column_selector as selector

categorical_columns_selector = selector(dtype_include=object)
categorical_columns = categorical_columns_selector(data)
categorical_columns

# or 

categorical_columns = [x for x in data.columns if adult_df[x].dtype == 'object']

categorical_columns

['workclass',
 'education',
 'marital-status',
 'occupation',
 'relationship',
 'race',
 'sex',
 'native-country']

In [10]:
data_categorical = data[categorical_columns]
data_categorical.head()

workclass      education       marital-status          occupation  \
0     Private           11th        Never-married   Machine-op-inspct   
1     Private        HS-grad   Married-civ-spouse     Farming-fishing   
2   Local-gov     Assoc-acdm   Married-civ-spouse     Protective-serv   
3     Private   Some-college   Married-civ-spouse   Machine-op-inspct   
4           ?   Some-college        Never-married                   ?   

  relationship    race      sex  native-country  
0    Own-child   Black     Male   United-States  
1      Husband   White     Male   United-States  
2      Husband   White     Male   United-States  
3      Husband   Black     Male   United-States  
4    Own-child   White   Female   United-States

### Encoding ordinal categories

* The most intutive strategy is to encode each category with a different number. 

### bracket을 두 개 쓰면 Dataframe으로 불러온다.

In [12]:
from sklearn.preprocessing import OrdinalEncoder

education_column = data_categorical[['education']]

encoder = OrdinalEncoder()
education_encoded = encoder.fit_transform(education_column)
education_encoded

array([[ 1.],
       [11.],
       [ 7.],
       ...,
       [11.],
       [11.],
       [11.]])

In [14]:
encoder.categories_

[array([' 10th', ' 11th', ' 12th', ' 1st-4th', ' 5th-6th', ' 7th-8th',
        ' 9th', ' Assoc-acdm', ' Assoc-voc', ' Bachelors', ' Doctorate',
        ' HS-grad', ' Masters', ' Preschool', ' Prof-school',
        ' Some-college'], dtype=object)]

In [19]:
data_encoded = encoder.fit_transform(data_categorical)
data_encoded[:5]

array([[ 4.,  1.,  4.,  7.,  3.,  2.,  1., 39.],
       [ 4., 11.,  2.,  5.,  0.,  4.,  1., 39.],
       [ 2.,  7.,  2., 11.,  0.,  4.,  1., 39.],
       [ 4., 15.,  2.,  7.,  0.,  2.,  1., 39.],
       [ 0., 15.,  4.,  0.,  3.,  4.,  0., 39.]])

### 알아두기
OrdinalEncoder uses a lexicographical(사전 순서대로) strategy to map string category labels to integers.InterruptedError

ex) Size 'S', 'M', 'L', 'XL' => 2, 1, 0, 3 by following the alphabetical OrdinalEncoder

In [24]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse=False)
education_encoded = encoder.fit_transform(education_column)

In [25]:
education_encoded

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

### Sparse matrix

행열에 포함된 0이 많은 경우, 데이터 공간을 아끼기 위해 필요한 정보만 수록한 행렬을 말한다.

![photo](data/6.png) 

In [27]:
feature_names = encoder.get_feature_names(input_features=['education'])
education_encoded = pd.DataFrame(education_encoded,columns=feature_names)
education_encoded

education_ 10th  education_ 11th  education_ 12th  education_ 1st-4th  \
0                  0.0              1.0              0.0                 0.0   
1                  0.0              0.0              0.0                 0.0   
2                  0.0              0.0              0.0                 0.0   
3                  0.0              0.0              0.0                 0.0   
4                  0.0              0.0              0.0                 0.0   
...                ...              ...              ...                 ...   
48837              0.0              0.0              0.0                 0.0   
48838              0.0              0.0              0.0                 0.0   
48839              0.0              0.0              0.0                 0.0   
48840              0.0              0.0              0.0                 0.0   
48841              0.0              0.0              0.0                 0.0   

       education_ 5th-6th  education_ 7th-8th  education_ 9th  \
0                     0.0                 0.0             0.0   
1                     0.0                 0.0             0.0   
2                     0.0                 0.0             0.0   
3                     0.0                 0.0             0.0   
4                     0.0                 0.0             0.0   
...                   ...                 ...             ...   
48837                 0.0                 0.0             0.0   
48838                 0.0                 0.0             0.0   
48839                 0.0                 0.0             0.0   
48840                 0.0                 0.0             0.0   
48841                 0.0                 0.0             0.0   

       education_ Assoc-acdm  education_ Assoc-voc  education_ Bachelors  \
0                        0.0                   0.0                   0.0   
1                        0.0                   0.0                   0.0   
2                        1.0                   0.0                   0.0   
3                        0.0                   0.0                   0.0   
4                        0.0                   0.0                   0.0   
...                      ...                   ...                   ...   
48837                    1.0                   0.0                   0.0   
48838                    0.0                   0.0                   0.0   
48839                    0.0                   0.0                   0.0   
48840                    0.0                   0.0                   0.0   
48841                    0.0                   0.0                   0.0   

       education_ Doctorate  education_ HS-grad  education_ Masters  \
0                       0.0                 0.0                 0.0   
1                       0.0                 1.0                 0.0   
2                       0.0                 0.0                 0.0   
3                       0.0                 0.0                 0.0   
4                       0.0                 0.0                 0.0   
...                     ...                 ...                 ...   
48837                   0.0                 0.0                 0.0   
48838                   0.0                 1.0                 0.0   
48839                   0.0                 1.0                 0.0   
48840                   0.0                 1.0                 0.0   
48841                   0.0                 1.0                 0.0   

       education_ Preschool  education_ Prof-school  education_ Some-college  
0                       0.0                     0.0                      0.0  
1                       0.0                     0.0                      0.0  
2                       0.0                     0.0                      0.0  
3                       0.0                     0.0                      1.0  
4                       0.0                     0.0                      1.0  
...                     .

In [28]:
data_encoded = encoder.fit_transform(data_categorical)

In [31]:
columns_encoded = encoder.get_feature_names(data_categorical.columns)
pd.DataFrame(data_encoded, columns=columns_encoded)

workclass_ ?  workclass_ Federal-gov  workclass_ Local-gov  \
0               0.0                     0.0                   0.0   
1               0.0                     0.0                   0.0   
2               0.0                     0.0                   1.0   
3               0.0                     0.0                   0.0   
4               1.0                     0.0                   0.0   
...             ...                     ...                   ...   
48837           0.0                     0.0                   0.0   
48838           0.0                     0.0                   0.0   
48839           0.0                     0.0                   0.0   
48840           0.0                     0.0                   0.0   
48841           0.0                     0.0                   0.0   

       workclass_ Never-worked  workclass_ Private  workclass_ Self-emp-inc  \
0                          0.0                 1.0                      0.0   
1                          0.0                 1.0                      0.0   
2                          0.0                 0.0                      0.0   
3                          0.0                 1.0                      0.0   
4                          0.0                 0.0                      0.0   
...                        ...                 ...                      ...   
48837                      0.0                 1.0                      0.0   
48838                      0.0                 1.0                      0.0   
48839                      0.0                 1.0                      0.0   
48840                      0.0                 1.0                      0.0   
48841                      0.0                 0.0                      1.0   

       workclass_ Self-emp-not-inc  workclass_ State-gov  \
0                              0.0                   0.0   
1                              0.0                   0.0   
2                              0.0                   0.0   
3                              0.0                   0.0   
4                              0.0                   0.0   
...                            ...                   ...   
48837                          0.0                   0.0   
48838                          0.0                   0.0   
48839                          0.0                   0.0   
48840                          0.0                   0.0   
48841                          0.0                   0.0   

       workclass_ Without-pay  education_ 10th  ...  native-country_ Portugal  \
0                         0.0              0.0  ...                       0.0   
1                         0.0              0.0  ...                       0.0   
2                         0.0              0.0  ...                       0.0   
3                         0.0              0.0  ...                       0.0   
4                         0.0              0.0  ...                       0.0   
...                       ...              ...  ...                       ...   
48837                     0.0              0.0  ...                       0.0   
48838                     0.0              0.0  ...                       0.0   
48839                     0.0              0.0  ...                       0.0   
48840                     0.0              0.0  ...                       0.0   
48841                     0.0              0.0  ...                       0.0   

       native-country_ Puerto-Rico  native-country_ Scotland  \
0                              0.0                       0.0   
1                              0.0                       0.0   
2                              0.0                       0.0   
3                              0.0                       0.0   
4                              0.0                       0.0   
...                            ...                       ...   
48837                          0.0                       0.0   
48838                  

### Choosing encoding strategy

* OneHotEncoder는 linear model에 좋다. 
* OrdinalEncoder는 tree-based models에 좋다. 

Linear models은 순서가 잘못된 카테고리(misordered categories)에 Tree models보다 더 영향을 많이 받는다.

물론 OrdinalEncoder를 쓸 순 있지만 몇가지 주의해서 사용해아한다.
* 해당 category가 ordinal이어야 함.
* encoded category와 원래 순서가 같아야함. 

OneHotEncoder는 attribute가 많이 생기기 때문에 tree 모델 계산에 드는 비용이 늘어나게 된다. 따라서 nominal인 attribute에도 OneHotEncoder를 추천한다. 


### Pipeline에 Encoder 포함하기

In [32]:
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import LogisticRegression

model = make_pipeline(
    OneHotEncoder(handle_unknown='ignore'), LogisticRegression(max_iter=500)
)

### handle_unknown

* OneHotEncoder에 포함되는 handle_unknown은 train_set에는 포함됐는데 test_set에는 포함되지 않아서 발생하는 오류를 없애는 용도로 사용된다.

* 어떤 membership 개수가 1개인데, train_set에 포함되지 않고 test_set에 포함되는 경우에는, 해당 membership은 encoding이 되지 않은 체로 남아있게 된다.

* 왜냐하면 make_pipeline을 통해 데이터가 train 된 후 그 모델을 가지고 testing을 진행하는 것이기 때문이다.

![photo](data/5.png)


In [33]:
from sklearn.model_selection import cross_validate
cv_results= cross_validate(model, data_categorical, target)
cv_results

{'fit_time': array([1.05250239, 0.91542673, 0.87652707, 0.97507691, 0.84884405]),
 'score_time': array([0.05023909, 0.03590059, 0.03026795, 0.03052545, 0.03095984]),
 'test_score': array([0.83222438, 0.83560242, 0.82872645, 0.83312858, 0.83466421])}

In [35]:
scores = cv_results['test_score']
print(f' score mean : {scores.mean(): .3f}, score std : {scores.std(): .3f}')

 score mean :  0.833, score std :  0.002
